### ISSUE TITLE
make file error

### ISSUE THREAD

**Issue by cooltechie** [waneck/linux-ios-toolchain#3]
Hi ,
First of all i would like to thank you for this great work, i was looking for something exactly like this. I am trying to build it on Ubuntu machine , i have installed all of the dependencies and i am trying to build the toolchain for "arm-apple-darwin" i.e :- ios but after configure when i try to make i seem to be getting stuck in an endless loop and following error message keeps showing up on screen -

/bin/sh: 1: cd: can't cd to build/cctools/cctools

Thanks & Regards,
Vineet Pant

**Comment by waneck** [comment]
Hi,
You must get the git submodule:
```
git submodule init
git submodule update
```

It should work then.
